fix: Update pipeline configuration for improved security checks and build process

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,4 +1,4 @@
-name: Sucure CI/(CD)
+name: build-and-test
 
 on:
   push:
@@ -11,23 +11,43 @@ env:
   FRONTEND_IMAGE: xxxx/react-frontend
   
 jobs:
-  security-and-build:
-    #if: github.ref_type == 'tag'
+  secret-scan:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v4
-
-      # --- VALIDATE TAG 
-      #- name: Validate Tag Format
-      #  run: echo $GITHUB_REF_NAME | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$'
 
       # --- SECRET SCAN
       - name: Secret Scan
         uses: gitleaks/gitleaks-action@v2
         with: 
           config_path: .gitleaks.toml
+  
+  security-check:
+    #if: github.ref_type == 'tag'
+    runs-on: ubuntu-latest
 
+    steps:
+      - uses: actions/checkout@v4
+
+      # --- VALIDATE TAG FORMAT
+      - name: Validate Tag Format
+        if: github.ref_type == 'tag'
+        run: echo $GITHUB_REF_NAME | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || (echo "Tag format is invalid. Use vMAJOR.MINOR.PATCH" && exit 1)
+
+      # --- BACKEND TEST
+      - name: Setup Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: '1.25.3'
+      
+      # --- TRY BUILD GO
+      - name: Go Build
+        run: cd backend && go build -o main ./cmd/api
+
+      # --- VET GO
+      - name: Go Vet
+        run: cd backend && go vet ./cmd/api
 #  build:
 
 #    runs-on: ubuntu-latest
